language: node_js
node_js:
- 4.3.1
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token: d091dae0064c4056986c37c2fadca597b267de4685c170acd6c069240e92922d
deploy:
  provider: npm
  email: technique@yocto.re
  api_key:
    secure: d2/gE6ddOdmlzURFtL2BtKfSLmyTJAYbpdKYavpz+PtXsSlF+QCf1Snh1suioJY5rmT9eZrF3Myvj7vcGI3BJ3bi+BEjXB0Tnk4CMy/WadGQPmzxNFilcAio8n5pk/Ervnk6ETYFMSVnON5Gtq7rzK/mR151iIgGqGijkljd9dVFtpAUxj5X/82/0hVauRTt2hB10X4qiHD5kvYfhcCbHz2trhpwGmrhAlwvIKHiDNtVZkJkJsYYeippVgWp8B0OilBEVqIhCGOeF7CH78ZI+NZa3forl7yb9dGX/NhbrsgungLleGspMeTbGLHK39ZBskpTzhFGGGeV8NWTlGmJBG5C0QZlw5/Bv2lNxOgEr2JH1UnRIY31IFEAioO76iPkjQapC1ny5W9T/vaiOPYKSFpquP6CvzIUp7ZLw778ja8msf1tP2e9itQprFDx4oRPSmHXJB34s+yGusTElNq0ml/yPIBV7zq4jC70xdOpX0VzOxOoSzY2tagWFS2F7YjesQHHyxaOPphPNvdqGt8cAqg3SOiF4cpVevuTKLgRWC0Ieytre7zkGBoeW0QiWYewlxx4OMmcGIwq3kdpC3OYUiNGothx3jx4gd7ujF3ahMW7USlBMSuPhF3XgzXlf0A7oGaiwN3JHjocshFX/M49h/XJ2wez8u+ZfXYKbt7WyzY=
  on:
    tags: true
    repo: yoctore/yocto-pm2-mongodb
before_install: npm install -g grunt-cli
install: npm install
